config/routes.rb
Rails.application.routes.draw do

	get 'signup' => 'users#new'
	get 'profile' => 'users#show'
	resources :users

	get 'login'   => 'sessions#new'
	get 'logout'  => 'sessions#destroy'
	resources :sessions

	get 'topseller' => 'photos#top_templates'
	resources :photos

  	resources :charges
  	resources :purchases, only: [:show]
  	resources :products 

  	get 'templates' => 'statics#templates'
  	get 'contact' => 'statics#contact'
  	get 'about' => 'statics#about'
  	get 'socialmedia' => 'statics#socialmedia'
    get 'tutorials' => 'statics#tutorials'
  	resources :statics
  
  	root 'statics#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

	def price_in_cents
		(self.price * 100).to_i
	end
	
end

app/models/purchase.rb
class Purchase < ApplicationRecord

	def to_param
		uuid
	end
	
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  

  def logged_in?
    @current_user != nil
  end

  helper_method :current_user, :logged_in?

  def authorize
    unless current_user
      redirect_to login_path
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def create
		product = Product.find(params[:product_id]) 
	  # Amount in cents
	 

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => product.price_in_cents,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )
	  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], 
	  	amount: product.price_in_cents, description: charge.description, currency: charge.currency,
	  	customer_id: customer.id, product_id: product.id, uuid: SecureRandom.uuid)

	  redirect_to purchase
	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@product = Product.find_by_sku("sfOne")
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def show
		@product = Product.find(params[:id])
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

	def show
		@purchase = Purchase.find_by_uuid(params[:id])
		@product = Product.find(@purchase.product_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if current_user
			redirect_to profile_path
		else
			render 'new'
		end	
	end

	def create
		user = User.find_by_email(user_params[:email])
		if user
			session[:user_id] = user.id
			redirect_to profile_path
		else
			redirect_to login_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
	
	private
		def user_params
			params.require(:user).permit(:email)
		end
		
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

	def home
		@products = Product.all
	end

	def top
	end

	def templates
		@products = Product.all
	end

	def contact
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		
		def new
			if current_user
				redirect_to profile_path(current_user)
			else
				@user = User.new
			end
		end

		def create
			if current_user
				redirect_to profile_path(current_user)
			else
				user = User.new(user_params)
				if user.save
					session[:user_id] = user.id
					redirect_to profile_path
				else
					redirect_to signup_path
				end
			end	
		end

		def show
			@user = User.find(session[:user_id])
		end

		def destroy
			@user = User.find(params[:id])
			if current_user
				@user.destroy
				session[:user_id] = nil
			else
	      		redirect_to root_path
			end
			
		end

		private
			def user_params
				params.require(:user).permit(:name, :email, :password)
			end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag 'favicon.png' %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Vividkick</title>
	<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/flatly/bootstrap.min.css">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  	<%= csrf_meta_tags %>	
	
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top" id="ciabatta">
		<div class="container-fluid" id="thenavbar">
	    	<div class="navbar-header">
	    		<ul class="nav navbar-nav pull-left">
	    			<!-- home -->
	    			<li id="home"><%= link_to "Vividkick", root_path, class: "home" %></li>
	    		</ul>
	    	    <section class="hamburger-button">	
	    		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	    			<span class="icon-bar"></span>
	    			<span class="icon-bar"></span>
	    			<span class="icon-bar"></span>
	    		</button>
	    		</section>	
	    	</div>
	    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    		<ul class="nav navbar-nav pull-right">
	    				<li id="hamburger"><%= link_to "Lightroom Presets", templates_path, class: "hamburger" %></li>	
	    			<% if logged_in? %>
						<li id="hamburger"><%= link_to "Profile", profile_path, class: "hamburger" %></li>	
						<li id="hamburger"><%= link_to "Log out", logout_path, class: "hamburger" %></li>								
					<% else %> 
						<li id="hamburger"><%= link_to "Login", login_path, class: "hamburger" %></li>
						<li id="hamburger"><%= link_to "Sign Up", signup_path, class: "hamburger" %></li>
					<% end %>
	    		</ul>
	    	</div>
		</div>
	</nav>

	<%= yield %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	
</body>

<!-- Footer -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4">	
			</div>
			<div class="col-md-4"></div>
		</div>
			<br>		
		<div class="row">
			<div class="col-md-3">
				<center><%= link_to "Contact Us", contact_path %></center>
			</div>
			<div class="col-md-3">
				<% if current_user %>
					<center><%= link_to "Account", profile_path %></center>
				<% else %>
					<center><%= link_to "Account", root_path %></center>
				<% end %>
			</div>
			<div class="col-md-3">
				<center><%= link_to "About", about_path %></center>
			</div>
			<div class="col-md-3">
				<center><%= link_to "Social Media", socialmedia_path %></center>
					<br>
	                <ul class="social-network social-circle">
		                <center>
		                     <li><a href="https://www.facebook.com/" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
		                     <li><a href="https://twitter.com/" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
		                     <li><a href="https://www.instagram.com/?hl=en" class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></a></li>
		                     <li><a href="https://www.pinterest.com/" class="icoPinterest" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
		                </center>
	                </ul>		
			</div>
		</div>
	</div>	
</footer>
	<br>
	<br>
	<br>
</html>

app/views/pages/home.html.erb
    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title">Your Product <span class="font-weight-light">Product Name</span></h1>
           

            <p>Lorem ipsum dolor sit amet, in nam feugiat eleifend. Sea an possit offendit definiebas, usu cu aeque mediocritatem. Vis constituam suscipiantur ad, cum duis concludaturque no. Sea vocent consulatu at.</p>

            <p>Lorem ipsum dolor sit amet, pri id tractatos torquatos, eruditi alienum eam ad. Sint graeci mel te. Ex eius corrumpit.</p>
            <p><strong>What You Get</strong></p>
            <ul class="no-indent">
                <li>Lorem ipsum dolor sit.</li>
                <li>Lorem ipsum dolor sit amet, cum.</li>
                <li>Lorem ipsum dolor sit amet, quo ne etiam.</li>
            </ul>
        </article>
        <aside id="details-aside" class="col-sm-4">
            

	            <%= form_tag charges_path, id:'chargeForm' do %>
	           
	                <% if flash[:error].present? %>
	                  <div id="error_explanation">
	                    <p><%= flash[:error] %></p>
	                  </div>
	                <% end %>

	              <script src="https://checkout.stripe.com/checkout.js"></script>
	              <%= hidden_field_tag 'stripeToken' %>
	              <%= hidden_field_tag 'amount', 499 %>
	              <%= hidden_field_tag 'stripeEmail' %>
	              <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>

              <script>
              	    var handler = StripeCheckout.configure({
              	      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
              	      token: function(token, arg) {
              	        document.getElementById("stripeToken").value = token.id;
              	        document.getElementById("stripeEmail").value = token.email;
              	        document.getElementById("chargeForm").submit();
              	      }
              	});
              	document.getElementById('btn-buy').addEventListener('click', function(e) {
              	      handler.open({
              	        name: 'One month',
              	        description: 'ciabatta ($4.99)',
              	        amount: 499
              	    });
              	    e.preventDefault();
              	   })
              	   </script>
	            <% end %>
            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">Info</li>
              <li class="list-group-item">What You Get</li>
              <li class="list-group-item">This Is Included</li>
            </ul>
        </aside>
    </section>


<!-- Scripts -->
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="js/lib/bootstrap.min.js"></script>

app/views/products/show.html.erb
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="js/lib/bootstrap.min.js"></script>
  <div>
      <center>
          <h1><%= @product.title %> - $<%= @product.price %></h1> 
      </center>   
  </div>
  <br>

<!-------- Product & Description Section ---------->

  <div class="container-fluid" id="container-description">
      <div class="row">
          <div class="col-md-6">
              <img src="<%= asset_path @product.image_name %>">

              <!--------- Stripe -------------->

                <div class="container">
                    <%= form_tag charges_path, id:'chargeForm' do %>

                        <% if flash[:error].present? %>
                          <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                          </div>
                        <% end %>

                      <script src="https://checkout.stripe.com/checkout.js"></script>
                      <%= hidden_field_tag 'stripeToken' %>
                      <%= hidden_field_tag 'amount', @product.price_in_cents %>
                      <%= hidden_field_tag 'stripeEmail' %>
                      <%= hidden_field_tag 'product_id', @product.id %>
                      <br>
                      <center>
                          <button id="btn-buy" type="button" class="btn btn-primary"><h4>Buy This!</h4></button>
                      </center>
                      
                    <script>
                          var handler = StripeCheckout.configure({
                            key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                            token: function(token, arg) {
                              document.getElementById("stripeToken").value = token.id;
                              document.getElementById("stripeEmail").value = token.email;
                              document.getElementById("chargeForm").submit();
                            }
                      });
                      document.getElementById('btn-buy').addEventListener('click', function(e) {
                            handler.open({
                              name: '<%= @product.subtitle %>',
                              description: '<%= @product.title %> ($<%= @product.price %>)',
                              amount: <%= @product.price_in_cents %>
                          });
                          e.preventDefault();
                         })
                         </script>
                    <% end %>
                </div>
          </div>
          <div class="col-md-6">
              <center>
                  <h2>Description</h2>
              </center>
              <br>
              <ul>
                  <li>(Ignore for now) <strong>Product's Title:</strong> <%= @product.title %></li>
                  <li>(Ignore for now) <strong>Product's Price:</strong> <%= @product.price %></li>
                  <li>(Ignore for now) <strong>Product's Info:</strong> <%= @product.info %></li>
              </ul>

              <!------- Comments ------------>
              
                    <div class="panel">
                        <p>
                          <center><h3>Comments</h3></center>
                          <ul>
                              <li>Lorem Ispsum</li>
                              <li>Lorem Ispsum</li>
                              <li>Lorem Ispsum</li>
                              <li>Lorem Ispsum</li>
                          </ul>
                        </p>
                    </div>
                        <center>
                            <p class="slide">
                              <div class="pull-me">
                                Show Comments
                              </div>
                            </p> 
                        </center>
                        
                 

                <script>
                    $(document).ready(function() {
                        $('.pull-me').click(function() {
                            $('.panel').slideToggle('slow')
                        })
                    })
                </script>
          </div>
      </div>   
  </div>






        

app/views/purchases/show.html.erb
<div class="container">
    <center>
        <h1>Your Order</h1>
    </center>
</div>
<div class="container">
    <div class="row">
            <img src="<%= asset_path @product.image_name %>">
    </div>
</div>
<div class="container">
    <div class="row">
    <br>
        <center>
            <a href="<%= @product.download_url %>">
            <button id="btn-buy" type="button" class="btn btn-primary">HERE IS YOUR PRESET</button></a>
        </center> 
    </div> 
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <center>
                <p>Thank You</p>
                <p><%= @product.title%></p>
                <p>$<%= @product.price %></p>
            </center>        
        </div>  
    </div>
</div>
<br>
<br>

app/views/statics/about.html.erb
<div class="container-fluid">
	<div class="row">
		<center>
			<h3>The Vividkick Team</h3>
		</center>
	</div>
	<br>
	<div class="row">
		<div class="col-md-6" >
			<center>
				<p>
					<h4>Erin</h4>
				</p>
				<img src="/assets/erin.png" id="erinpicture">
			</center>	
		</div>
		<div class="col-md-6" >
			<center>
				<p>
					<h4>Tim</h4>
				</p>
				<img src="/assets/tim.png" id="timpicture">
			</center>
		</div>
	</div>
</div>

app/views/statics/contact.html.erb
<div class="container-fluid">
	<div class="row">
		<center>
			<h1>Hi I'm Flash, how can I help?</h1>
		</center>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<center>
				<img src="/assets/flash.png" id="flashpicture">
			</center>	
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<center>
				<h3>
				Email me questions at flash@vividkick.com
				</h3>
			</center>
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-3">
			<h3><%= link_to "Tutorials", tutorials_path %></h3>
		</div>
	</div>
</div>

app/views/statics/home.html.erb
<!-- Section for the main image and box -->
<section>
	<div class="main-picture">
		<div class="main-image"></div>
		<div class="right-box">
			<h1>
			<center id="box">BEST SELLER</center>
			</h1>
			<p>
				<h3>Lightroom Presets</h3>
			</p>
			<p>
				<h4 id="edit">Edit photos to your liking<h4>
			</p>
			<center>
				<%= link_to "VIEW DETAILS", templates_path, class: "btn btn-primary" %>
			</center>	
		</div>
	</div>	
</section>

<!-- Section for where the picture of the Lightroom are show -->

<div class="container" >
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<center>
				<h2 id="title"><%= link_to "BEST SELLERS", templates_path %></h2>
			</center>	
		</div>
		<div class="col-md-4">
		</div>
	</div>
	<br>	
</div>	

<!-- Lightroom Presets Section -->
<div class="container-fluid">
	<div class="row" id="templates">
		<% @products.each do |product| %>
		<div class="col-md-3">
			<a href="<%= product_path(product) %>">
				<div class="product-image-container" id="star">
					<div class="star">
						<img src="<%= asset_path product.image_name %>" class="picture" id="picture"/>
						<br>
						<br>
						<center>
							<button class="btn btn-primary">LEARN MORE</button>
						</center>
					</div>
				</div>
			</a>
		</div>
		<% end %>
		<br>
		<br>
	</div>
</div>


<!-- Section explaing what Vividkick does -->

<!-- <div class="container-fluid" id="smiley">
	<div class="row" id="star">
		<div class="col-md-4">
			<div class="star">
				<br>
				<center>
					<span class="glyphicon glyphicon-grain" id="grain"></span>
				</center>
			</div>			 
		</div>
		<div class="col-md-8">
			<div class="star">
				<ul class="custom-bullet">
				    <li><h4>Vivid allows you to edit photos to your liking</h4></li>
				    <li><h4>Lightroom presets are a pre-determined position of all or some of the sliders in Lightroom</h4></li>
				    <li><h4>Ciabatta</h4></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<br>
<br> -->


<!--------- jQuery for fading in -------->
 <script src="//code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>

    <script>
	    function showImages(el) {
	        var windowHeight = jQuery( window ).height();
	        $(el).each(function(){
	            var thisPos = $(this).offset().top;

	            var topOfWindow = $(window).scrollTop();
	            if (topOfWindow + windowHeight - 200 > thisPos ) {
	                $(this).addClass("fadeIn");
	            }
	        });
	    }

	    // if the image in the window of browser when the page is loaded, show that image
	    $(document).ready(function(){
	            showImages('.star');
	    });

	    // if the image in the window of browser when scrolling the page, show that image
	    $(window).scroll(function() {
	            showImages('.star');
	    });
</script>

<!-- jQuery for hoving over picture and changing background color -->
<script>
	$(function() {
	   $('.picture').hover( function(){
	      $(this).css('background-color', '#92d7d0');
	   },
	   function(){
	      $(this).css('background-color', '#ffffff');
	   });
	});
</script>

app/views/statics/socialmedia.html.erb
<div class="container-fluid">
	<div class="row">
		<center>
			<h3>Social Media</h3>
		</center>
	</div>
</div>

app/views/statics/templates.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<center>
				<h2>Lightroom Presets</h2>
			</center>
			<p>Lightroom presets are a pre-determined position of all or some of the sliders in Lightroom</p>
		</div>
	</div>
</div>
<br>

<!--------- Section for where the products are shown ------------>
<div>
	<div class="row" id="templates">
		<% @products.each do |product| %>
		<div class="col-md-4" id="column">
			<section>
				<a href="<%= product_path(product) %>">
					<div class="product-image-container">
						<br>
						<br>
						<br>
						<center>
							<img src="<%= asset_path product.image_name %>" class="picture" id="picture"/>
						</center>
						
					</div>	
				</a>
				<br>
				<br>
				<p id="product-title">
					<h3>
						<center><%= product.title %></center>
					</h3>
				</p>
				<p>
					<h3>
						<center>$<%= product.price %></center>
					</h3>
				</p>
				<br>
			</section>
		</div>
		<% end %>
	</div>
</div>
<br>


<!-- jQuery to make pictures bigger -->

 <script src="//code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>

<script>
	$(function() {
		$('.picture').hover( function(){
			$(this).addClass('transition');

		}, function() {
			$('.picture').removeClass('transition');
		});
	});
</script>

app/views/statics/tutorials.html.erb
<div class="container-fluid">
	<div class="row">
		<center>
			<h3>Learn How To Use Presets</h3>
		</center>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>Sign Up</h1>
		<%= form_for @user do |f| %>
		<p>
		<%= f.text_field :name, placeholder: "Name" %>	
		</p>
		<p>
		<%= f.email_field :email, placeholder: "Emial" %>	
		</p>
		<p>
		<%= f.password_field :password, placeholder: "Password" %>	
		</p>
		<%= f.submit "Sign Up", class: "btn btn-primary" %>
		<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<p>
		<h1><%= current_user.name %></h1>
	</p>
</div>